## Config file

# Log 
seed: 777
use_cuda: 1           # 1 for True, 0 for False #todo 这里待确认怎么修改mps

# dataset
speaker_no: 2
mix_lst_path: ./data/wsj0_2mix/
audio_direc: /mnt/nas_sg/wulanchabu/zexu.pan/datasets/
reference_direc: /mnt/nas_sg/wulanchabu/zexu.pan/datasets/
audio_sr: 8000
ref_sr: 8000

# dataloader
num_workers: 4
batch_size: 4         # 2-GPU training with a total effective batch size of 8
accu_grad: 0
effec_batch_size: 4   # per GPU, only used if accu_grad is set to 1, must be multiple times of batch size
max_length: 4         # truncate the utterances in dataloader, in seconds 

# network settings
init_from: None       # 'None' or a log name 'log_2024-07-22(18:12:13)'
causal: 0             # 1 for True, 0 for False
network_reference:
  cue: speech            # lip or speech or gesture or EEG
network_audio:
  backbone: SpEx-plus
  L: 20
  N: 256
  X: 8
  R: 4
  B: 256
  H: 512
  P: 3
  norm: gLN
  non_linear: relu
  speakers: 101       # 101 speakers in wsj0-2mix training set

# optimizer
loss_type: SpEx-plus     # spex loss in paper
init_learning_rate: 0.001
max_epoch: 200
clip_grad_norm: 5
